# Generated by Django 5.0.6 on 2024-07-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('title_tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_time_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
