# Generated by Django 5.0.6 on 2024-08-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/default-image.jpeg', null=True, upload_to='images/'),
        ),
    ]
